### PR TITLE
Fix-file-browser

### LINKED ISSUE #142: Hide Unsupported "files" when attempting to upload things in GDrive
When attempting to showcase the gdrive files, we shouldn't be showing files that are not "uploadale" (aka google sheets, google docs, google slides...)

### LINKED ISSUE #176: Selecting Files in Picker Is Buggy
https://github.com/uNotesOfficial/upup/assets/43147238/b416a9fb-d3e9-4cb8-9e5a-2c3c54b83a19

### LINKED ISSUE #194: sometimes file previews break (google's fault)

### PR DESCRIPTION
**Pull request by MohamedBechirMejri**
Fixes #142 #176 #194

### CODE REVIEW

File: src/components/UpupUploader/FileBrowser/ListItem.tsx [hunk 1]
```diff
@@ -51,33 +51,53 @@ const ListItem = ({
...
     }
-    const initial: Target = {
+
+    const transition: AnimationProps['transition'] = {
+        type: 'spring',
+        damping: 10,
+        stiffness: 100,
+        opacity: { delay: index * 0.05 },
+        y: { delay: index * 0.05 },
+    }
```
Comment (bassem97) [inline src/components/UpupUploader/FileBrowser/ListItem.tsx:61]: Is it better to declare this in component scope rather than file gloabal file scope

File: src/components/UpupUploader/FileBrowser/ListItem.tsx [hunk 2]
```diff
@@ -51,33 +51,53 @@ const ListItem = ({
...
         ...backgroundColor,
     }
 
-    const animate: Target = {
+    const animate: AnimationProps['animate'] = {
         opacity: 1,
         y: 0,
         ...backgroundColor,
+        transition,
     }
```
Comment (bassem97) [inline src/components/UpupUploader/FileBrowser/ListItem.tsx:74]: those one too ?

**Review by bassem97 — CHANGES_REQUESTED** [review]
Great job

File: src/components/UpupUploader/FileBrowser/ListItem.tsx (hunk 2 above)
Comment (MohamedBechirMejri) [reply src/components/UpupUploader/FileBrowser/ListItem.tsx:74]: I tried moving them outside the component but they require some vars from the component.

either way I don't like that code so we'll have to find a fix for the build error eventually

File: src/components/UpupUploader/FileBrowser/ListItem.tsx (hunk 1 above)
Comment (MohamedBechirMejri) [reply src/components/UpupUploader/FileBrowser/ListItem.tsx:61]: will refactor the code another time.

**Review by bassem97 — APPROVED** [review]
LGTM
