### PR TITLE
fixing the style of  upupUploader

### LINKED ISSUE #37: Find a proper layout for UpupUploader
we need to make a new layout for those 3 component the upload, gdrive and oneDrive components, maybe we put the buttons side by side and increase the padding between them !
image

### PR DESCRIPTION
**Pull request by arijhajji-1**
image

### CODE REVIEW

File: src/UpupUploader.tsx [hunk 1]
```diff
@@ -82,11 +92,19 @@ export const UpupUploader: FC<UpupUploaderProps> = ({
...
+            {components[uploadAdapter]}
+        </SpacedComponent>
     ))
 
     /**
      *  Return the selected components
      */
-    return <>{selectedComponent}</>
+    return (
+        <>
```
Comment (bassem97) [inline src/UpupUploader.tsx]: you don't need those diamonds here !

File: src/components/FileUploader/FileUploader.tsx [hunk 2]
```diff
@@ -203,12 +208,11 @@ const FileUploader = ({
...
 
                         <StyledParagraph>
-                            <StyledSpan>Click to upload</StyledSpan> or drag and
-                            drop PDF, DOC, DOCX OR TXT (MAX. 10MB)
+                            <StyledSpan>Click to upload</StyledSpan>
                         </StyledParagraph>
 
                         <StyledSmallParagraph>
-                            {/*SVG, PNG, JPG or GIF (MAX. 800x400px)*/}
+                            or drag and drop PDF, DOC, DOCX OR TXT (MAX. 10MB)
```
Comment (bassem97) [inline src/components/FileUploader/FileUploader.tsx:215]: don't forget that we re using upup to upload course and school images too !

**Review by bassem97 — APPROVED** [review]
All good
